module.exports = {
  plugins: ['react-native', 'react', 'jsx-a11y', 'import', '@typescript-eslint'],
  rules: {
    'import/prefer-default-export': 'off',
    'import/no-extraneous-dependencies': 'off',
    'import/no-unresolved': 'off',
    'no-console': ['error', { allow: ['warn', 'error', 'info'] }],
    camelcase: 'off',
    'global-require': 'off',
    'no-extend-native': 'off',
    'no-loop-func': 'off',
    'jsx-a11y/no-autofocus': 'off',
    'react/forbid-prop-types': 'off',
    'react-native/no-unused-styles': 'error',
    'no-param-reassign': 'off',
    'no-async-promise-executor': 'off',
    'func-names': 'off',
    '@typescript-eslint/no-explicit-any': 'off',
  },
};
