name: auto-merge

on:
  pull_request:
    branches: [ main ]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          target: minor
          command: squash and merge
          github-token: ${{ secrets.DEPENDABOT_ACTION_TOKEN }}
